### ISSUE TITLE
undefined method `kill' for nil:NilClass when building image

### ISSUE THREAD

**Issue by dklassen** [Shopify/linecook-gem#2]
```
─klassen at klassen in ~/code/shopify/cookbooks/linecook on master✘✘✘ using ‹2.1.8›
╰─± bx linecook bake -n data-chi
Starting xhyve guest...
Started with e2:63:2f:14:cf:32... waiting for network
undefined method `kill' for nil:NilClass
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/builder/darwin_backend.rb:73:in `launch_guest'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/builder/darwin_backend.rb:33:in `start'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/builder/manager.rb:23:in `start'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/builder/build.rb:13:in `initialize'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/provisioner/manager.rb:13:in `new'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/provisioner/manager.rb:13:in `bake'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/cli.rb:147:in `bake'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/bin/linecook:8:in `block in <top (required)>'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/bin/linecook:8:in `<top (required)>'
/Users/klassen/.rbenv/versions/2.1.8/bin/linecook:23:in `load'
/Users/klassen/.rbenv/versions/2.1.8/bin/linecook:23:in `<main>'
/Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/builder/darwin_backend.rb:73:in `launch_guest': undefined method `kill' for nil:NilClass (NoMethodError)
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/builder/darwin_backend.rb:33:in `start'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/builder/manager.rb:23:in `start'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/builder/build.rb:13:in `initialize'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/provisioner/manager.rb:13:in `new'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/provisioner/manager.rb:13:in `bake'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/lib/linecook/cli.rb:147:in `bake'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/bin/linecook:8:in `block in <top (required)>'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
    from /Users/klassen/.rbenv/versions/2.1.8/lib/ruby/gems/2.1.0/gems/linecook-gem-0.5.8/bin/linecook:8:in `<top (required)>'
    from /Users/klassen/.rbenv/versions/2.1.8/bin/linecook:23:in `load'
    from /Users/klassen/.rbenv/versions/2.1.8/bin/linecook:23:in `<main>'
```

**Comment by dklassen** [comment]
may not have been on latest master
